import Head from 'next/head'
import { Inter } from 'next/font/google'
import Menu from '@/components/Menu'
import Sobre from '@/components/Sobre'
import Projetos from '@/components/Projetos'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>José Eugênio - Meu Portfólio Pessoal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu/>
      <Sobre/>
      <Projetos/>
      <Footer/>
    </>
  )
}
