import Head from 'next/head'
import Home from '@/components/Home'
import Sobre from '@/components/Sobre'
import Projetos from '@/components/Projetos'
import Footer from '@/components/Footer'
import Tecnologias from '@/components/Tecnologias'

export default function Index() {
  return (
    <>
      <Head>
        <title>José Eugênio - Meu Portfólio Pessoal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home/>
      <Sobre/>
      <Projetos/>
      <Tecnologias/>
      <Footer/>
    </>
  )
}
